// inference_pipeline/frontend/app.js
const API_BASE_URL = (window.__API_BASE__ || "http://localhost:8000").replace(/\/+$/, "");
const LANG_LABELS = {en:"English",ta:"தமிழ்",hi:"हिन्दी",bn:"বাংলা",te:"తెలుగు",ml:"മലയാളം",kn:"ಕನ್ನಡ",mr:"मराठी",gu:"ગુજરાતી"};
const PLACEHOLDERS = {en:"Ask your question...",ta:"உங்கள் கேள்வியை கேளுங்கள்...",hi:"अपना प्रश्न पूछें...",bn:"আপনার প্রশ্ন জিজ্ঞাসা করুন...",te:"మీ ప్రశ్న అడగండి...",ml:"നിങ്ങളുടെ ചോദ്യമുയര്‍ത്തുക...",kn:"ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",mr:"आपला प्रश्न विचारा...",gu:"તમારો પ્રશ્ન પૂછો..."};
const API_TIMEOUT_MS = 20000;
let sessionId = crypto.randomUUID ? crypto.randomUUID() : ('sess-'+Math.random().toString(36).slice(2));
let history = [];
const $ = id => document.getElementById(id);
function setStatus(text, isError=false, busy=false){const el=$('status');el.textContent=text||'';el.style.color=isError?'#b00020':'#444';$('voiceDot').classList.toggle('recording', busy);}
function clearResults(){$('answers').innerHTML='';$('sources').innerHTML='';}
function shortDomain(url){try{const u=new URL(url);return u.hostname}catch(e){return url||''}}
function renderAnswers(lines){const container=$('answers');container.innerHTML='';if(!lines||!lines.length){container.textContent='Unable to provide an answer.';return}lines.forEach((ln,i)=>{const div=document.createElement('div');div.className='answer-line';const num=document.createElement('strong');num.textContent=(i+1)+'. ';const span=document.createElement('span');span.textContent=(typeof ln==='string')?ln:(ln.text||'');div.appendChild(num);div.appendChild(span);container.appendChild(div)});container.focus()}
function renderSources(citations,sourcesList){const s=$('sources');s.innerHTML='';const seen=new Set();(citations||[]).forEach(c=>{const url=c.source_url||c.source||'';if(!url||seen.has(url))return;seen.add(url);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=`[${c.citation||''}] ${shortDomain(url)}`;a.className='citation-link';s.appendChild(a)});(sourcesList||[]).forEach(url=>{if(!url||seen.has(url))return;seen.add(url);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=shortDomain(url);a.className='citation-link';s.appendChild(a)})}
function pushHistory(q,res){history.unshift({ts:Date.now(),q,res});const h=$('history');h.innerHTML='';history.slice(0,20).forEach(it=>{const d=document.createElement('div');d.textContent=`${new Date(it.ts).toLocaleString()} • ${it.q}`;h.appendChild(d)})}
async function doQuery(payload){setStatus('Searching...',false,true);$('askBtn').disabled=true;try{const ctrl=new AbortController();const to=setTimeout(()=>ctrl.abort(),API_TIMEOUT_MS);const r=await fetch(API_BASE_URL+'/v1/query',{method:'POST',headers:{"Content-Type":"application/json; charset=utf-8"},body:JSON.stringify(payload),signal:ctrl.signal});clearTimeout(to);if(!r.ok){setStatus('Server error: '+r.status,true);$('askBtn').disabled=false;return null}const body=await r.json();$('askBtn').disabled=false;setStatus('');return body}catch(err){$('askBtn').disabled=false;if(err.name==='AbortError'){setStatus('Request timed out.',true)}else{setStatus('Network error.',true)}return null}finally{setStatus('',false,false)}}
async function ask(){clearResults();const q=$('query').value.trim();if(!q){setStatus('Please enter a question.',true);return}const lang=$('lang').value||'en';const reqId=crypto.randomUUID?crypto.randomUUID():('r-'+Date.now());const payload={channel:'web',language:lang,query:q,session_id:sessionId,request_id:reqId};const res=await doQuery(payload);if(!res){pushHistory(q,{resolution:'error'});return}if(res.resolution==='answer'){renderAnswers(res.answer_lines||res.answer_lines||[{text:res.answer_lines?res.answer_lines:res.answer||''}]);renderSources(res.citations||[],res.sources||[]);setStatus('Answer ready');pushHistory(q,res);if(res.tts_url){playTtsUrl(res.tts_url)}else{speakAnswer(res.answer_lines||res.answer_lines||[{text:res.answer||''}],lang)}}else{const reason=(res.guidance_key||res.reason||res.resolution);if(reason==='not_enough_info'){setStatus({'en':'No authoritative information found.','ta':'அதிகாரப்பூர்வ தகவல் இல்லை.','hi':'प्राधिकृत जानकारी नहीं मिली.'}[lang]||'No authoritative information found.',true)}else{setStatus('Unable to provide an answer.',true)}pushHistory(q,res)}}
function speakAnswer(lines,lang){let txt='';if(Array.isArray(lines)){for(const l of lines){txt += (typeof l==='string'?l:(l.text||'')) + ' '}}else txt=lines||'';try{const s=window.speechSynthesis;if(!s){return}const utter=new SpeechSynthesisUtterance(txt);utter.lang=lang;window.speechSynthesis.cancel();window.speechSynthesis.speak(utter)}catch(e){}}
async function playTtsUrl(url){try{const a=new Audio(url);await a.play()}catch(e){}}
function applyPlaceholder(){const lang=$('lang').value||'en';$('query').placeholder=PLACEHOLDERS[lang]||PLACEHOLDERS.en;$('askBtn').textContent={'en':'Ask','ta':'கேளுங்கள்','hi':'पूछें'}[lang]||'Ask'}
$('askBtn').addEventListener('click',ask);$('clearBtn').addEventListener('click',()=>{ $('query').value=''; clearResults(); setStatus('') });$('lang').addEventListener('change',applyPlaceholder);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){ask()}});applyPlaceholder()
let recognition=null;let lastConfidence=0
function supportsSpeech(){return 'webkitSpeechRecognition' in window || 'SpeechRecognition' in window}
function createRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR) return null; const r=new SR(); r.lang=$('lang').value||'en'; r.interimResults=false; r.maxAlternatives=1; return r}
$('voiceBtn').addEventListener('click',async ()=>{if(!supportsSpeech()){setStatus('Voice not supported in this browser',true);return} if(!recognition){recognition=createRecognition(); if(!recognition){setStatus('Voice not available',true);return} recognition.onstart=()=>{setStatus('Listening...',false,true);$('voiceBtn').setAttribute('aria-pressed','true')}; recognition.onerror=(ev)=>{setStatus('Voice error',true);$('voiceBtn').setAttribute('aria-pressed','false')} ; recognition.onresult=async (ev)=>{const r=ev.results[0][0];const transcript=r.transcript || ''; lastConfidence = (r.confidence||0); $('query').value = transcript; $('voiceBtn').setAttribute('aria-pressed','false'); setStatus('Recognized. Sending...',false); const payload={channel:'voice',language:$('lang').value||'en',query:transcript,session_id:sessionId,request_id:crypto.randomUUID?crypto.randomUUID():('r-'+Date.now()),asr_confidence:lastConfidence}; const res = await doQuery(payload); if(res && res.resolution==='answer'){renderAnswers(res.answer_lines||[{text:res.answer||''}]);renderSources(res.citations||[],res.sources||[]); setStatus('Answer ready'); pushHistory(transcript,res); if(res.tts_url) playTtsUrl(res.tts_url); else speakAnswer(res.answer_lines||[{text:res.answer||''}],$('lang').value)} else { setStatus('No authoritative information found.',true); pushHistory(transcript,res) } }; recognition.onend=()=>{setStatus('',false,false);$('voiceBtn').setAttribute('aria-pressed','false')}; recognition.start(); } else { try{ recognition.stop(); recognition=null; $('voiceBtn').setAttribute('aria-pressed','false'); setStatus('') }catch(e){ recognition=null; setStatus('') } }});
